### ISSUE TITLE
QG checks (Release 24.03)

### ISSUE THREAD

**Issue by tomaszbarwicki** [eclipse-tractusx/puris#257] opened 2024-02-21 10:32 UTC
## QG checks
Please keep this issue open until QG is concluded and will be managed by the Issue Creator!
We will inform you about finding and proposals in separated issues, this issue here is for the Overview of the Checks!

### Please keep this issue open until QG is concluded!

Product Owner: Ute Burkhardt
Dev SPOC: @tom-rm-meyer-ISST
Helm Chart Version: 1.0.0 (to set in release)
App Version: 1.0.0 (to set in release)

Release Managemnet Reference Issue: updates https://github.com/eclipse-tractusx/sig-release/issues/510

### Check of Tractus-X Release Guidelines

- Currently implemented automatic checks can be found under your product on our [Release Guidelines Checks Board](https://eclipse-tractusx.github.io/sig-release/) 
- This QG Check is depending on the mandatory information from our current [Release Guidelines](https://eclipse-tractusx.github.io/docs/release)

#### TRG 1 Documentation

- [x] [TRG 1.01](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-1) appropriate `README.md` 
- [x] [TRG 1.02](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-2) appropriate install instructions either `INSTALL.md` or in `README.md`
- [x] [TRG 1.03](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-3) appropriate `CHANGELOG.md`
- [x] [TRG 1.04](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-4) editable static files

#### TRG 2 Git

- [x] [TRG 2.01](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-1) default branch is named `main`
- [x] [TRG 2.03](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-3) repository structure
- [x] [TRG 2.04](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-4) leading product repository
- [x] [TRG 2.05](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5) `.tractusx` metafile in a proper format

#### TRG 3 Kubernetes

- [x] [TRG 3.02](https://eclipse-tractusx.github.io/docs/release/trg-3/trg-3-2) persistent volume and persistent volume claim is used when needed

#### TRG 4 Container

- [x] [TRG 4.01](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-01) [semantic versioning](https://semver.org/) and tagging 
- [x] [TRG 4.02](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-02) base image is agreed  
- [x] [TRG 4.03](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-03) image has `USER` command and Non Root Container
- [x] [TRG 4.05](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-05) released image must be placed in `DockerHub`, remove `GHCR` references 
- [x] [TRG 4.06](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-06) separate notice file for `DockerHub` has all necessary information

#### TRG 5 Helm

- [x] [TRG 5.01](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-01) Helm chart requirements
- [x] [TRG 5.02](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-02) Helm chart location in `/charts` directory and correct structure
- [x] [TRG 5.03](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-03) proper version strategy 
- [x] [TRG 5.04](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-04) CPU / MEM resource requests and limits and are properly set
- [x] [TRG 5.06](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-06) Application must be configurable through the Helm chart 
- [x] [TRG 5.07](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-07) Dependencies are present and properly configured in the Chart.yaml
- [x] [TRG 5.08](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-08) Product has a single deployable helm chart that contains all components 
- [x] [TRG 5.09](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-09) Helm Test running properly
- [x] [TRG 5.10](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-10) Products need to support 3 versions at a time
- [x] [TRG 5.11](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-11) Upgradeability
 
#### TRG 6 Released Helm Chart

- [x] [TRG 6.01](https://eclipse-tractusx.github.io/docs/release/trg-6/trg-6-1) Released Helm Chart 

#### TRG 7 Open Source Governance
- [x] [TRG 7.01](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-01) Legal Documentation
- [x] [TRG 7.02](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) License and copyright header  
- [x] [TRG 7.03](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-03) IP checks for project content 
- [x] [TRG 7.04](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04) IP checks for 3rd party content
- [x] [TRG 7.05](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-05) Legal information for distributions
- [x] [TRG 7.06](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-06) Legal information for end user content
- [x] [TRG 7.07](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-07) Legal notice for documentation
- [x] [TRG 7.08](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-08) Legal notice for KIT documentation

#### Information Sharing

**Comment by tomaszbarwicki** [comment] 2024-02-21 10:33
Hi @tom-rm-meyer-ISST,

would you mind providing following information for 24.03 release?

Product Owner:
Dev SPOC:
Helm Chart Version:
App Version: 

thanks in advance.

**Comment by tom-rm-meyer-ISST** [comment] 2024-02-21 10:39
> Hi @tom-rm-meyer-ISST,
> 
> would you mind providing following information for 24.03 release?
> 
> Product Owner: Dev SPOC: Helm Chart Version: App Version:
> 
> thanks in advance.

Hey @tomaszbarwicki. Currently versions look a bit different but I would go for 1.0.0 for all as this is our first release.

Product Owner: Ute Burkhardt
Dev SPOC: @tom-rm-meyer-ISST 
Helm Chart Version: 1.0.0 (to set in release)
App Version: 1.0.0 (to set in release)

**Comment by tomaszbarwicki** [comment] 2024-02-21 10:44
@tom-rm-meyer-ISST: thanks for prompt response. I don't see any branch/tags for 1.0.0 release, is main fine for quality checks in this case?

**Comment by tom-rm-meyer-ISST** [comment] 2024-02-21 10:50
> @tom-rm-meyer-ISST: thanks for prompt response. I don't see any branch/tags for 1.0.0 release, is main fine for quality checks in this case?

Yes, I have the meeting in 10 minutes. Wanted to ask them whether I already should create a release / branch (first time).

**Comment by tom-rm-meyer-ISST** [comment] 2024-02-21 11:27
> @tom-rm-meyer-ISST: thanks for prompt response. I don't see any branch/tags for 1.0.0 release, is main fine for quality checks in this case?

@tomaszbarwicki shall I prepare a Release branch with the associated versions? Shall I already release a chart? Feel free to ping me in CX MS Teams.

**Comment by tomaszbarwicki** [comment] 2024-02-22 10:37
Hi @tom-rm-meyer-ISST, any update on release? So far I created the 3 issues above and continue reiviewing whatever I can at main branch. 

Question on the additional package you install on top of base image in the frontend Dockerfile "moreutils". We actually don't recommend doing that because of security reasons. However I'm trying to understand the reason for it in your case. Could 'sponge' usage in the start-nginx.sh be simply replaced by output redirection i.e.


`envsubst $EXISTING_VARS < /etc/nginx/nginx.conf > sponge /etc/nginx/nginx.conf`

**Comment by tomaszbarwicki** [comment] 2024-02-22 11:35
> I can create a release. I would first incorporate your findings and then create a release. Or should I create a release candidate upfront?

The thing is that without a release I can't review certain points i.e. helm test release, helm test workflow runs properly, that it supports 3 k8s versions. semantic versioning and tagging.
Let's agree that if I finish what I can based on main branch I'll let you know and you can create release after incorporating the findings so I can proceed further.
> 
> Regarding sponge: we initially tried it using tee. Problem is that tee, does not allow directly replacing multiple environment variables and has a restricition of characters it can handle. This restriction results in problems when saving the file and thus does not allow replacement of the envirionment variables.

Did you try this? Would that work?

`envsubst $EXISTING_VARS < /etc/nginx/nginx.conf > /etc/nginx/nginx.conf`

**Comment by tom-rm-meyer-ISST** [comment] 2024-02-22 14:14
> > I can create a release. I would first incorporate your findings and then create a release. Or should I create a release candidate upfront?
> 
> The thing is that without a release I can't review certain points i.e. helm test release, helm test workflow runs properly, that it supports 3 k8s versions. semantic versioning and tagging. Let's agree that if I finish what I can based on main branch I'll let you know and you can create release after incorporating the findings so I can proceed further.
> 
> > Regarding sponge: we initially tried it using tee. Problem is that tee, does not allow directly replacing multiple environment variables and has a restricition of characters it can handle. This restriction results in problems when saving the file and thus does not allow replacement of the envirionment variables.
> 
> Did you try this? Would that work?
> 
> `envsubst $EXISTING_VARS < /etc/nginx/nginx.conf > /etc/nginx/nginx.conf`

Confirmed first.

**Comment by tomaszbarwicki** [comment] 2024-02-23 09:29
hi @tom-rm-meyer-ISST can you please confirm and help me understand how you implement https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-06/ ?

**Comment by tom-rm-meyer-ISST** [comment] 2024-02-23 09:43
> hi @tom-rm-meyer-ISST can you please confirm and help me understand how you implement https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-06/ ?

we have a [view](https://github.com/eclipse-tractusx/puris/blob/main/frontend/src/views/AboutLicense.vue), that links to that. It loads data from the following [json](https://github.com/eclipse-tractusx/puris/blob/main/frontend/src/assets/aboutPage.json) that needs to be set during release process.

Frontend screenshot:
![image](https://github.com/eclipse-tractusx/puris/assets/116013795/2d513d95-717c-41a3-9921-c1ca6973ae15)

**Comment by tomaszbarwicki** [comment] 2024-02-23 11:03
@tom-rm-meyer-ISST crated one more issue for users' ids used in the Dockerfiles vs helm chart. That exhausts the checks I'm able to do without release in place, rest I can continue afterwards.

**Comment by tom-rm-meyer-ISST** [comment] 2024-02-26 15:15
Chart releaser action currently not working due to missing repository configuration. Created PR for otterdog: https://github.com/eclipse-tractusx/.eclipsefdn/pull/57

**Comment by tom-rm-meyer-ISST** [comment] 2024-02-27 06:05
> Chart releaser action currently not working due to missing repository configuration. Created PR for otterdog: [eclipse-tractusx/.eclipsefdn#57](https://github.com/eclipse-tractusx/.eclipsefdn/pull/57)

PR has been merged, Chart releaser, now works:
![image](https://github.com/eclipse-tractusx/puris/assets/116013795/390946e6-1e3d-4305-9f0c-e4d228ee26b7)

**Closed** 2024-02-29 15:08 UTC
